---
- name: Add Microsoft Key
  become: yes
  become_method: sudo
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Vscode repository
  become: yes
  become_method: sudo
  apt_repository: repo="deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
  tags: vscode

- name: Install code package
  apt: name=code state=installed
  become: yes
  become_method: sudo