---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
  become: yes
  become_method: sudo

- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  become: yes
  become_method: sudo

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true
  become: yes
  become_method: sudo

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
    state: present
    update_cache: yes
  become: yes
  become_method: sudo

- name: Install Docker.
  package: name=docker-ce state=present
  become: yes
  become_method: sudo

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- group:
    name: docker
    state: present
  become: yes
  become_method: sudo

- name: Adding jlafourc to group docker
  user: name='jlafourc'
        groups=docker
        append=yes
  become: yes
  become_method: sudo